#!/bin/bash

#
#  _____    __  __   _                 _____    ______   ____     ____    _____    _   _ 
# |  __ \  |  \/  | | |               |  __ \  |  ____| |  _ \   / __ \  |  __ \  | \ | |
# | |__) | | \  / | | |               | |__) | | |__    | |_) | | |  | | | |__) | |  \| |
# |  ___/  | |\/| | | |               |  _  /  |  __|   |  _ <  | |  | | |  _  /  | . ` |
# | |      | |  | | | |____           | | \ \  | |____  | |_) | | |__| | | | \ \  | |\  |
# |_|      |_|  |_| |______|          |_|  \_\ |______| |____/   \____/  |_|  \_\ |_| \_|
#                             ______                                                     
#                            |______|                                                    
#
# < --- under the GPLv3 license / https://github.com/denisebitca/pml_reborn --- >
# < --- based on jmaia's work available at https://github.com/jerem-ma/pimp_my_lock --->
#
# timing might be a little odd, if anyone wants to test the script on 42Paris Macs,
# it would be kind
#
#

# LD_LIBRARY_PATH for xdotool
export LD_LIBRARY_PATH=$PWD/lib

# PATH for ease of writing
export PATH=$PATH:$PWD/bin

# For debugging: false = no ft_lock, true = ft_lock
export LOCKME=$1

if [[ "$LOCKME" == "true" ]]; then
	until grep '"ft_lock":' <(xwininfo -tree -root) > /dev/null; do
		ft_lock
		sleep 1
	done
fi

# Want to change how your video is placed on screen? edit mpv.conf.
./mplayer_wrapper
sleep 1

if [[ "$LOCKME" == "true" ]]; then
	node websocket_client.js $(cat $PWD/domain) & #if you are not using a websocket server, comment this!
	pid=$! #if you are not using a websocket server, comment this!
	while pgrep -f "ft_lock +-d" > /dev/null; do
		w_id=$(xwininfo -root -tree | grep ft_lock | head -n 1 | sed 's/ *\(0x[a-z0-9]\+\).*/\1/')
		xdotool click 1 #comment this if you want your screen to shut off on idle!
		sleep 1
	done
	kill -INT $pid #if you are not using a websocket server, comment this!
	pkill mpv
	exit 0;
fi

node websocket_client.js $(cat $PWD/domain) #if you are not using a websocket server, comment this!

# 
# if you don't want to be able to change your lockscreen on the fly
# by using a websocket server (https://github.com/denisebitca/pml_wss),
# use this instead of node
#
# sleep 2
# ./control_mplayer <absolute path/network location>
#
