#!/bin/bash

# LD_LIBRARY_PATH for xdotool
export LD_LIBRARY_PATH=$PWD/lib

# PATH for ease of writing
export PATH=$PATH:$PWD/bin

if [[ ! -p /tmp/mplay_ft_lock ]]; then
	mkfifo /tmp/mplay_ft_lock
fi

mplayer -x $1 \
		-title "pml_reborn" \
		-vf scale \
		-zoom \
		-geometry $2 \
		-idle \
		-quiet \
		-slave \
		-input file=/tmp/mplay_ft_lock 2>&1 &
