#!/bin/bash

# LD_LIBRARY_PATH for xdotool
export LD_LIBRARY_PATH=$PWD/lib

# PATH for ease of writing
export PATH=$PATH:$PWD/bin

mpv --title="pml_reborn" \
	--ontop \
	--idle \
	--no-audio \
	--config=yes \
	--hwdec \
	--config-dir=. \
	--input-ipc-server=/tmp/mplay_ft_lock 2>&1 &
